### ISSUE TITLE
imaginary got stuck

### ISSUE THREAD

**Issue by wirtsi** [h2non/imaginary#104]
This weekend imaginary got stuck/locked without any visible cause.

We are at around 20-30 req/s doing resizing on images pulled from GCS, balanced in a Kubernetes cluster of 5 pods. It appears all of them got stuck at around the same time.

The logs give me

```
17:51:38.000
goroutine 549781 [syscall, locked to thread]:
17:51:38.000
gopkg.in/h2non/bimg%2ev1._Cfunc_vips_affine_interpolator(0x7fb4f9b56650, 0xc4215f27d0, 0x3fe0cccccccccccd, 0x0, 0x0, 0x3fe0cccccccccccd, 0x7fb5959500f0, 0x0)
17:51:38.000
??:0 +0x50
17:51:38.000
gopkg.in/h2non/bimg%2ev1.vipsAffine(0x7fb4f9b56650, 0x3fe0cccccccccccd, 0x3fe0cccccccccccd, 0x0, 0x0, 0x0, 0x0)
17:51:38.000
/go/src/gopkg.in/h2non/bimg.v1/vips.go:489 +0x321
17:51:38.000
gopkg.in/h2non/bimg%2ev1.transformImage(0x7fb4f9b56650, 0xd2, 0xd2, 0x0, 0x0, 0x0, 0x0, 0x5a, 0x6, 0x0, ...)
17:51:38.000
/go/src/gopkg.in/h2non/bimg.v1/resize.go:183 +0xd0
17:51:38.000
gopkg.in/h2non/bimg%2ev1.Resize(0xc4350a0000, 0x3e750, 0x3fe00, 0xd2, 0xd2, 0x0, 0x0, 0x0, 0x0, 0x5a, ...)
17:51:38.000
/go/src/gopkg.in/h2non/bimg.v1/resize.go:95 +0x9d4
17:51:38.000
main.Process(0xc4350a0000, 0x3e750, 0x3fe00, 0xd2, 0xd2, 0x0, 0x0, 0x0, 0x0, 0x5a, ...)
17:51:38.000
/go/src/github.com/h2non/imaginary/image.go:220 +0x124
17:51:38.000
main.Resize(0xc4350a0000, 0x3e750, 0x3fe00, 0xd2, 0xd2, 0x0, 0x0, 0x5a, 0x0, 0x0, ...)
17:51:38.000
/go/src/github.com/h2non/imaginary/image.go:75 +0x156
17:51:38.000
main.Operation.Run(0x732b18, 0xc4350a0000, 0x3e750, 0x3fe00, 0xd2, 0xd2, 0x0, 0x0, 0x5a, 0x0, ...)
17:51:38.000
/go/src/github.com/h2non/imaginary/image.go:21 +0xc1
17:51:38.000
main.imageHandler(0xa50280, 0xc420459780, 0xc420b9b950, 0xc4350a0000, 0x3e750, 0x3fe00, 0x732b18, 0x2328, 0x64, 0x0, ...)
17:51:38.000
/go/src/github.com/h2non/imaginary/controllers.go:85 +0x1b2
17:51:38.000
main.imageController.func1(0xa50280, 0xc420459780, 0xc420b9b950)
17:51:38.000
/go/src/github.com/h2non/imaginary/controllers.go:50 +0x237
17:51:38.000
net/http.HandlerFunc.ServeHTTP(0xc4200cd2a0, 0xa50280, 0xc420459780, 0xc420b9b950)
17:51:38.000
/usr/local/go/src/net/http/server.go:1726 +0x44
17:51:38.000
main.defaultHeaders.func1(0xa50280, 0xc420459780, 0xc420b9b950)
17:51:38.000
/go/src/github.com/h2non/imaginary/middleware.go:117 +0x1d4
17:51:38.000
net/http.HandlerFunc.ServeHTTP(0xc4200cd2c0, 0xa50280, 0xc420459780, 0xc420b9b950)
17:51:38.000
/usr/local/go/src/net/http/server.go:1726 +0x44
17:51:38.000
main.validate.func1(0xa50280, 0xc420459780, 0xc420b9b950)
17:51:38.000
/go/src/github.com/h2non/imaginary/middleware.go:77 +0x163
17:51:38.000
net/http.HandlerFunc.ServeHTTP(0xc4200cd2e0, 0xa50280, 0xc420459780, 0xc420b9b950)
17:51:38.000
/usr/local/go/src/net/http/server.go:1726 +0x44
17:51:38.000
main.validateImage.func1(0xa50280, 0xc420459780, 0xc420b9b950)
17:51:38.000
/go/src/github.com/h2non/imaginary/middleware.go:94 +0xc1
17:51:38.000
net/http.HandlerFunc.ServeHTTP(0xc4200cd300, 0xa50280, 0xc420459780, 0xc420b9b950)
17:51:38.000
/usr/local/go/src/net/http/server.go:1726 +0x44
17:51:38.000
net/http.(*ServeMux).ServeHTTP(0xc420015e60, 0xa50280, 0xc420459780, 0xc420b9b950)
17:51:38.000
/usr/local/go/src/net/http/server.go:2022 +0x7f
17:51:38.000
main.(*LogHandler).ServeHTTP(0xc4200cd8a0, 0xa50500, 0xc429fb7d40, 0xc420b9b950)
17:51:38.000
/go/src/github.com/h2non/imaginary/log.go:75 +0x1e8
17:51:38.000
net/http.serverHandler.ServeHTTP(0xc420088380, 0xa50500, 0xc429fb7d40, 0xc420b9b950)
17:51:38.000
/usr/local/go/src/net/http/server.go:2202 +0x7d
17:51:38.000
net/http.(*conn).serve(0xc420459600, 0xa50ac0, 0xc4211dcb40)
17:51:38.000
/usr/local/go/src/net/http/server.go:1579 +0x4b7
17:51:38.000
created by net/http.(*Server).Serve
17:51:38.000
/usr/local/go/src/net/http/server.go:2293 +0x44d
```

Unfortunately the status endpoint still thought everything was swell, so this impacted the other pods in the cluster by generating too much load a bit

I'm afraid that this is still a bit hazy but perhaps you can see from the trace what might have happened.

Bests

**Comment by h2non** [comment]
I'm sorry for the issue.

There's no too useful info there, but apparently, it's a `cgo` issue.
I found this related issue in Go: https://github.com/golang/go/issues/16714

If you can only reproduce this issue while reaching a specific traffic concurrency, I would suggest you to enable the traffic throttler limiter in `imaginary`, configuring it up to 15 o 18 req/sec.

It would be hard for me to reproduce that, so if you have specific large images you're processing, that would help. I think in some case might be related to the memory pressure of processing large images.

Moreover, I saw what you said about the `health` endpoint and I will think about how to improve and provide a more trustful server status there.

**Comment by wirtsi** [comment]
No worries, your software has been behaving really well ... the odd hickup is probably to be expected :)

I'll try to figure out what exactly went wrong there. On the weekend, I was busy getting everything up and running again so I didn't try to gather infos.

Bests & thanks for your help

**Comment by scott-seo** [comment]
FYI,

I was experiencing the same exact issue while I was using libvips 8.4.1 and Go 1.7.1 

I have tried latest bimg from master github branch, Go 1.8.1 and libvips 8.5.4, so far so good. I have over 30 goroutines resizing images. 

I am running my own web server instead of imaginary.

**Comment by Dynom** [comment]
@wirtsi do you have any feedback regarding this issue, if not, feel free to close it.

**Comment by h2non** [comment]
There is no evidence about potential persistent issues here. Closing.
