### ISSUE TITLE
imaginary crashing ..

### ISSUE THREAD

**Issue by foobargeez** [h2non/imaginary#233]
I am running v1.0.16 and the crash is happening with one image in particular .. let me know if you want me to upload the image.

```
2019/01/08 11:30:42 http: panic serving 192.168.168.4:37948: interface conversion: interface {} is nil, not int
goroutine 1095 [running]:
net/http.(*conn).serve.func1(0xc0000b0820)
        /usr/local/go/src/net/http/server.go:1746 +0xd0
panic(0x6fb600, 0xc000091e90)
        /usr/local/go/src/runtime/panic.go:513 +0x1b9
main.mapImageParams(0xc0006a4420, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /go/src/github.com/h2non/imaginary/params.go:123 +0x12f6
main.readMapParams(0xc000091920, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /go/src/github.com/h2non/imaginary/params.go:90 +0x684
main.Pipeline(0xc000440000, 0x864df, 0x866df, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /go/src/github.com/h2non/imaginary/image.go:349 +0x169
main.Operation.Run(0x76dbe8, 0xc000440000, 0x864df, 0x866df, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /go/src/github.com/h2non/imaginary/image.go:45 +0xcd
main.imageHandler(0x7ae160, 0xc000924180, 0xc000918000, 0xc000440000, 0x864df, 0x866df, 0x76dbe8, 0x1f98, 0x64, 0x0, ...)
        /go/src/github.com/h2non/imaginary/controllers.go:106 +0x203
main.imageController.func1(0x7ae160, 0xc000924180, 0xc000918000)
        /go/src/github.com/h2non/imaginary/controllers.go:52 +0x1ad
net/http.HandlerFunc.ServeHTTP(0xc0000995e0, 0x7ae160, 0xc000924180, 0xc000918000)
        /usr/local/go/src/net/http/server.go:1964 +0x44
main.authorizeClient.func1(0x7ae160, 0xc000924180, 0xc000918000)
        /go/src/github.com/h2non/imaginary/middleware.go:128 +0x199
net/http.HandlerFunc.ServeHTTP(0xc000099600, 0x7ae160, 0xc000924180, 0xc000918000)
        /usr/local/go/src/net/http/server.go:1964 +0x44
main.defaultHeaders.func1(0x7ae160, 0xc000924180, 0xc000918000)
        /go/src/github.com/h2non/imaginary/middleware.go:135 +0x134
net/http.HandlerFunc.ServeHTTP(0xc000099620, 0x7ae160, 0xc000924180, 0xc000918000)
        /usr/local/go/src/net/http/server.go:1964 +0x44
main.validate.func1(0x7ae160, 0xc000924180, 0xc000918000)
        /go/src/github.com/h2non/imaginary/middleware.go:95 +0x10d
net/http.HandlerFunc.ServeHTTP(0xc000099640, 0x7ae160, 0xc000924180, 0xc000918000)
        /usr/local/go/src/net/http/server.go:1964 +0x44
main.validateImage.func1(0x7ae160, 0xc000924180, 0xc000918000)
        /go/src/github.com/h2non/imaginary/middleware.go:112 +0xe7
net/http.HandlerFunc.ServeHTTP(0xc000099660, 0x7ae160, 0xc000924180, 0xc000918000)
        /usr/local/go/src/net/http/server.go:1964 +0x44
net/http.(*ServeMux).ServeHTTP(0xc000091140, 0x7ae160, 0xc000924180, 0xc000918000)
        /usr/local/go/src/net/http/server.go:2361 +0x127
main.(*LogHandler).ServeHTTP(0xc000099680, 0x7ae3e0, 0xc0008380e0, 0xc000918000)
        /go/src/github.com/h2non/imaginary/log.go:75 +0x1c3
net/http.serverHandler.ServeHTTP(0xc00009b040, 0x7ae3e0, 0xc0008380e0, 0xc000918000)
        /usr/local/go/src/net/http/server.go:2741 +0xab
net/http.(*conn).serve(0xc0000b0820, 0x7ae6a0, 0xc00001a240)
        /usr/local/go/src/net/http/server.go:1847 +0x646
created by net/http.(*Server).Serve
        /usr/local/go/src/net/http/server.go:2851 +0x2f5
```

**Comment by Dynom** [comment]
Yes please upload the photo, you can just paste it in a Github comment field to have Github host it for you. Although you can't easily delete it then.

**Comment by Dynom** [comment]
Could you also reply with your Pipeline instructions? Or perhaps include all details around the request you're making. That'll make it quite a bit easier to properly reproduce.

**Comment by foobargeez** [comment]
The image is -- https://pbs.twimg.com/media/DwX-vRdUYAACZ0x.jpg

The URL/pipeline is - `https://<host>/pipeline?file=%2Ftest%2FDwX-vRdUYAACZ0x.jpg&operations=%5B%7B%22operation%22%3A%22resize%22%2C%22params%22%3A%7B%22quality%22%3A70%2C%22noprofile%22%3Atrue%2C%22stripmeta%22%3Atrue%2C%22nocrop%22%3Atrue%2C%22width%22%3A%22865%22%7D%7D%5D`

**Comment by foobargeez** [comment]
Ahh ... that's silly issue on my side.  I found the issue in my code where this is erroneously getting treated as a string.  Thanks and sorry for wasting your time!

**Comment by Dynom** [comment]
Not at all, happy that I could help and as I said. We can definitely improve on the error handling here. Cheers!
