### ISSUE TITLE
Panic when trying to invoke /pipeline via get

### ISSUE THREAD

**Issue by roffe** [h2non/imaginary#236]
```
2019/01/15 23:20:41 http: panic serving 10.0.117.36:30644: interface conversion: interface {} is nil, not int
goroutine 2685 [running]:
net/http.(*conn).serve.func1(0xc000402280)
	/usr/local/go/src/net/http/server.go:1746 +0xd0
panic(0x7fb860, 0xc0004d8f30)
	/usr/local/go/src/runtime/panic.go:513 +0x1b9
main.mapImageParams(0xc000266368, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/h2non/imaginary/params.go:123 +0x12f6
main.readMapParams(0xc0004d8900, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/h2non/imaginary/params.go:90 +0x684
main.Pipeline(0xc00066e000, 0x8249d, 0xffe00, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/h2non/imaginary/image.go:351 +0x169
main.Operation.Run(0x886470, 0xc00066e000, 0x8249d, 0xffe00, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/h2non/imaginary/image.go:45 +0xcd
main.imageHandler(0x929dc0, 0xc0000f6100, 0xc0003cc000, 0xc00066e000, 0x8249d, 0xffe00, 0x886470, 0x2328, 0x64, 0xa, ...)
	/go/src/github.com/h2non/imaginary/controllers.go:106 +0x203
main.imageController.func1(0x929dc0, 0xc0000f6100, 0xc0003cc000)
	/go/src/github.com/h2non/imaginary/controllers.go:52 +0x1ad
net/http.HandlerFunc.ServeHTTP(0xc0001e0660, 0x929dc0, 0xc0000f6100, 0xc0003cc000)
	/usr/local/go/src/net/http/server.go:1964 +0x44
github.com/h2non/imaginary/vendor/gopkg.in/throttled/throttled%2ev2.(*HTTPRateLimiter).RateLimit.func1(0x929dc0, 0xc0000f6100, 0xc0003cc000)
	/go/src/github.com/h2non/imaginary/vendor/gopkg.in/throttled/throttled.v2/http.go:73 +0x192
net/http.HandlerFunc.ServeHTTP(0xc0001e06c0, 0x929dc0, 0xc0000f6100, 0xc0003cc000)
	/usr/local/go/src/net/http/server.go:1964 +0x44
main.defaultHeaders.func1(0x929dc0, 0xc0000f6100, 0xc0003cc000)
	/go/src/github.com/h2non/imaginary/middleware.go:135 +0x134
net/http.HandlerFunc.ServeHTTP(0xc0001e06e0, 0x929dc0, 0xc0000f6100, 0xc0003cc000)
	/usr/local/go/src/net/http/server.go:1964 +0x44
main.validate.func1(0x929dc0, 0xc0000f6100, 0xc0003cc000)
	/go/src/github.com/h2non/imaginary/middleware.go:95 +0x10d
net/http.HandlerFunc.ServeHTTP(0xc0001e0700, 0x929dc0, 0xc0000f6100, 0xc0003cc000)
	/usr/local/go/src/net/http/server.go:1964 +0x44
main.validateImage.func1(0x929dc0, 0xc0000f6100, 0xc0003cc000)
	/go/src/github.com/h2non/imaginary/middleware.go:112 +0xe7
net/http.HandlerFunc.ServeHTTP(0xc0001e0720, 0x929dc0, 0xc0000f6100, 0xc0003cc000)
	/usr/local/go/src/net/http/server.go:1964 +0x44
main.validateURLSignature.func1(0x929dc0, 0xc0000f6100, 0xc0003cc000)
	/go/src/github.com/h2non/imaginary/middleware.go:190 +0x303
net/http.HandlerFunc.ServeHTTP(0xc0001e0740, 0x929dc0, 0xc0000f6100, 0xc0003cc000)
	/usr/local/go/src/net/http/server.go:1964 +0x44
net/http.(*ServeMux).ServeHTTP(0xc0001a0900, 0x929dc0, 0xc0000f6100, 0xc0003cc000)
	/usr/local/go/src/net/http/server.go:2361 +0x127
main.(*LogHandler).ServeHTTP(0xc0001e0760, 0x92a040, 0xc0005040e0, 0xc0003cc000)
	/go/src/github.com/h2non/imaginary/log.go:75 +0x1c3
net/http.serverHandler.ServeHTTP(0xc00019da00, 0x92a040, 0xc0005040e0, 0xc0003cc000)
	/usr/local/go/src/net/http/server.go:2741 +0xab
net/http.(*conn).serve(0xc000402280, 0x92a340, 0xc00021c080)
	/usr/local/go/src/net/http/server.go:1847 +0x646
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:2851 +0x2f5
```

`/pipeline?operations=%5B%7B%22operation%22:%22resize%22,%22ignore_failure%22:%22false%22,%22params%22:%7B%22force%22:%22true%22,%22format%22:%22webp%22,%22height%22:%221600%22,%22nocrop%22:%22true%22,%22type%22:%22webp%22,%22width%22:%222088%22%7D%7D%5D&url=https://static.zerochan.net/Tachibana.Makoto.full.1578613.jpg&sign=wQF8UqZG4yPSJdxXt01NsasHTiN-B_fLygSB21gNGY8`

**Comment by Dynom** [comment]
Thanks again @roffe for feedback!

I was working on a branch that I started based on the information in this ticket https://github.com/h2non/imaginary/issues/233 to improve the feedback. In the process I also made the parameter handling more robust. When I have time for it this week I'll see if I can merge it back by then.

**Comment by Dynom** [comment]
I'm not sure if https://github.com/h2non/imaginary/pull/239 will be accepted.

However I've refactored parameter handling a bit and it should at least be more clear what blows up and hopefully it'll be a bit more forgiving and correct when handling parameters.

**Comment by Dynom** [comment]
The panic is resolved after merging in https://github.com/h2non/imaginary/pull/239 and with the new [1.0.17](https://github.com/h2non/imaginary/releases/tag/v1.0.17) release.

Thanks again for your feedback and by extension improving Imaginary!
