### ISSUE TITLE
Crash with background option

### ISSUE THREAD

**Issue by soullivaneuh** [h2non/imaginary#345]
With the following svg to png conversion request:

```
http --quiet --form --download --output "${png_path}" POST https://imagine.nexylan.dev/convert \
	stripmeta==true \
	lossless==true \
	type==png \
	background==white \
	file@"${svg_path}"
```

Imagine end in a crash with the following report:

```
2021/01/27 09:29:27 http: panic serving 172.18.0.12:51660: runtime error: index out of range [1] with length 1
goroutine 756 [running]:
net/http.(*conn).serve.func1(0xc000360000)
        /usr/local/go/src/net/http/server.go:1800 +0x139
panic(0x77d860, 0xc0000b42c0)
        /usr/local/go/src/runtime/panic.go:975 +0x3e3
main.BimgOptions(0x0, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /go/src/github.com/h2non/imaginary/options.go:148 +0x489
main.Convert(0xc00007b000, 0x4dd, 0xe00, 0x0, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /go/src/github.com/h2non/imaginary/image.go:304 +0x1bb
main.Operation.Run(...)
        /go/src/github.com/h2non/imaginary/image.go:48
main.imageHandler(0x82be40, 0xc000052080, 0xc00026e000, 0xc00007b000, 0x4dd, 0xe00, 0x7c2cc0, 0x2328, 0x64, 0x14, ...)
        /go/src/github.com/h2non/imaginary/controllers.go:120 +0x206
main.imageController.func1(0x82be40, 0xc000052080, 0xc00026e000)
        /go/src/github.com/h2non/imaginary/controllers.go:60 +0x3e6
net/http.HandlerFunc.ServeHTTP(0xc0000a7840, 0x82be40, 0xc000052080, 0xc00026e000)
        /usr/local/go/src/net/http/server.go:2041 +0x44
gopkg.in/throttled/throttled%2ev2.(*HTTPRateLimiter).RateLimit.func1(0x82be40, 0xc000052080, 0xc00026e000)
        /go/pkg/mod/gopkg.in/throttled/throttled.v2@v2.0.3/http.go:73 +0x1df
net/http.HandlerFunc.ServeHTTP(0xc0000a78a0, 0x82be40, 0xc000052080, 0xc00026e000)
        /usr/local/go/src/net/http/server.go:2041 +0x44
main.defaultHeaders.func1(0x82be40, 0xc000052080, 0xc00026e000)
        /go/src/github.com/h2non/imaginary/middleware.go:135 +0x1ff
net/http.HandlerFunc.ServeHTTP(0xc0000a78c0, 0x82be40, 0xc000052080, 0xc00026e000)
        /usr/local/go/src/net/http/server.go:2041 +0x44
main.validate.func1(0x82be40, 0xc000052080, 0xc00026e000)
        /go/src/github.com/h2non/imaginary/middleware.go:95 +0x145
net/http.HandlerFunc.ServeHTTP(0xc0000a78e0, 0x82be40, 0xc000052080, 0xc00026e000)
        /usr/local/go/src/net/http/server.go:2041 +0x44
main.validateImage.func1(0x82be40, 0xc000052080, 0xc00026e000)
        /go/src/github.com/h2non/imaginary/middleware.go:112 +0x144
net/http.HandlerFunc.ServeHTTP(0xc0000a7900, 0x82be40, 0xc000052080, 0xc00026e000)
        /usr/local/go/src/net/http/server.go:2041 +0x44
net/http.(*ServeMux).ServeHTTP(0xc0000adc80, 0x82be40, 0xc000052080, 0xc00026e000)
        /usr/local/go/src/net/http/server.go:2416 +0x1a5
main.(*LogHandler).ServeHTTP(0xc0001e80c0, 0x82c100, 0xc0001ea0e0, 0xc00026e000)
        /go/src/github.com/h2non/imaginary/log.go:76 +0x1c3
net/http.serverHandler.ServeHTTP(0xc0001ea000, 0x82c100, 0xc0001ea0e0, 0xc00026e000)
        /usr/local/go/src/net/http/server.go:2836 +0xa3
net/http.(*conn).serve(0xc000360000, 0x82c840, 0xc0000ac040)
        /usr/local/go/src/net/http/server.go:1924 +0x86c
created by net/http.(*Server).Serve
        /usr/local/go/src/net/http/server.go:2962 +0x35c
```

This bug comes from the `background` option (working fine without it).

Here is the related svg file: [500px.svg.gz](https://github.com/h2non/imaginary/files/5879084/500px.svg.gz)

Note: The files is provided as a `.gz` because github does not support svg upload (:upside_down_face:), but the uncompressed svg version is sent to the API.

**Comment by soullivaneuh** [comment]
Possible duplicates (or related) of:

- https://github.com/h2non/imaginary/issues/245
- https://github.com/h2non/imaginary/issues/324
